Feature tests
Ch0k/stackoverflow pull request #3
Opened 2021-11-11 14:53 UTC by Ch0k

2021-11-12 08:51 UTC, vkurennov requested changes

2021-11-12 08:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
нельзя делать редирект при ошибках валидации, во-первых, потеряется информация об ошибках, во-вторых, потеряется то, что ввел пользователь. поэтому надо делать рендер страницы с формой, в данном случае это questions/show

2021-11-12 08:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:question_id])
у тебя уже есть метод set_question, зачем дублировать?

2021-11-12 08:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
>  class AnswersController < ApplicationController
а где аутентификация?!

2021-11-12 08:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      @answer.destroy
тут должна быть проверка на автора, согласно заданию. и нам такая проверка понадобится еще не раз, поэтому лучше сразу сделать метод-предикат в модели User (например, `author_of?`), который определяет является ли пользователь автором преданного объекта. И не забудь тесты модели на этот метод

2021-11-12 08:51 UTC, vkurennov commented on app/controllers/questions_controller.rb
>    def destroy
нужна проверка на автора

2021-11-12 08:51 UTC, vkurennov commented on app/views/answers/new.html.erb
> +<%#= form_with model: @answer do |f| %>
на этом блоке мы используем slim для видов

2021-11-12 08:51 UTC, vkurennov commented on app/views/layouts/_navbar.html.erb
> +<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
нужно "перевести" на slim, есть автоматические конверторы

2021-11-12 08:51 UTC, vkurennov commented on app/views/questions/show.html.erb
> +<% if @question.user == current_user %>
вот проверка на автора, но во-первых, нужно еще и на уровне контроллера проверять, а во-вторых, в таком виде она не оптимальная, потому что грузит ассоциацию user у вопроса, т.е. делает лишний запрос и тратит память. Сравнивать лучше по user_id (а присваивать по объектам и ассоциациям, т.е. без _id)

2021-11-12 08:51 UTC, vkurennov commented on app/views/questions/show.html.erb
> +    <% if answer.user == current_user %>
а вот и дублирование проверки, как раз тут и видно, что лучше сделать метод `User#author_of?`
но тут еще и классическая проблема n+1 запроса из-за неоптимального сравнения: 1 запрос на загрузку всех ответов вопроса (в контроллере происходит) и затем, **для каждого** ответа еще по одному запросу на загрузку юзера. В итоге, для 10 ответов будет 11 запросов. Если же сравнивать по user_id, то запрос будет только 1. И такой маленькой оптимизацией мы вдруг ускорили этот блок в 10 раз (грубо)

2021-11-12 08:51 UTC, vkurennov commented on app/views/questions/show.html.erb
> +      <a data-method="delete" href="/questions/<%= @question.id %>/answers/<%= answer.id %>">Delete answer</a>
используй хелперы link_to и url-хелперы для построения ссылок

2021-11-12 08:51 UTC, vkurennov commented on config/routes.rb
>      resources :answers
объяви ресурс как shallow и не придется передавать question_id там, где он не нужен, например, в ссылке на удаление ответа

2021-11-12 08:51 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: {answer: attributes_for(:answer), question_id: question, user_id: user} }.to change(Answer,:count).by(1)
1. user_id не передается в параметрах, мы его в контроллере устанавливаем через current_user (это касается и тестов ниже)
2. в change лучше использовать question.answers первым прааметром, так сразу и связь с ответом проверим

2021-11-12 08:51 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
где тесты на destroy? сразу учти, что там 2 контекста: для автора и для не-автора

2021-11-12 08:51 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: {question: attributes_for(:question, user_id: user)} }.to change(Question,:count).by(1)
не нужно передавать user_id в параметрах

2021-11-12 08:51 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
тут 2 контекста должно быть: для автора и для не-автора

2021-11-12 08:51 UTC, vkurennov commented on spec/factories/answers.rb
>      association :question
если имя ассоциации и фабрики совпадает, то можно не писать `association`, а указывать имя ассоциации как метод, это сокращенный синтаксис:

```
 factory :answer do
    question
    # ...
end
```

2021-11-12 08:51 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    click_on 'Delete answer'
перед удалением стоит проверить, что контент ответа есть на странице

2021-11-12 08:51 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    expect(page).to have_content "Answer deleted"
этого недостаточно, сообщение может появиться, но это не означает, что ответ удален. надо проверить, что его больше нет на страниуе

2021-11-12 08:51 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    click_on 'Delete question'
тут то же самое: перед удалением надо проверить наличие вопроса на странице, а после - его отсутсвие

2021-11-12 08:51 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    answers.each do |answer|
тест верный, но т.к. все ответы одинаковые, он пройдет, даже если на странице только 1 ответ выведен, т.е. тест может быть ложно-положительным. решение: в фабриках через sequence сделать ответы разными

2021-11-12 08:51 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    fill_in 'Body', with: 'new answer answer answer'
создание ответа - это отдельная фича, и там, как и в создании вопроса, есть несколько сценриев (успешное создание, ошибки валидации, незалоигненный юзер)

2021-11-12 08:51 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    expect(page).to have_content 'Answer successfuly created'
опять же проверка сообщения проверяет лишь то, что на странице есть это сообщение, но никак не доказывает, что ответ тоже появился. грубо говоря, если ты в контроллере ответов в экшене create удалишь код, ответсвенный за создание ответа, а оставишь только код, создающий такое сообщение, то тесто пройдет. А значит, он не слишком полезен, если не тестирует главную функциональность фичи

2021-11-12 15:54 UTC, Ch0k commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Ok

2021-11-12 15:55 UTC, Ch0k commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:question_id])
Ok

2021-11-12 15:55 UTC, Ch0k commented on app/controllers/questions_controller.rb
>    def destroy
ok

2021-11-12 16:17 UTC, Ch0k commented on app/controllers/answers_controller.rb
>      @answer.destroy
ok

2021-11-14 21:16 UTC, Ch0k commented on app/controllers/answers_controller.rb
>  class AnswersController < ApplicationController
ok

2021-11-14 21:17 UTC, Ch0k commented on app/views/answers/new.html.erb
> +<%#= form_with model: @answer do |f| %>
ok

2021-11-14 21:17 UTC, Ch0k commented on app/views/layouts/_navbar.html.erb
> +<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
ok

2021-11-14 21:17 UTC, Ch0k commented on config/routes.rb
>      resources :answers
ok

2021-11-14 21:18 UTC, Ch0k commented on spec/factories/answers.rb
>      association :question
ok

2021-11-14 21:50 UTC, Ch0k commented on app/views/questions/show.html.erb
> +<% if @question.user == current_user %>
ok

2021-11-14 21:52 UTC, Ch0k commented on app/views/questions/show.html.erb
> +      <a data-method="delete" href="/questions/<%= @question.id %>/answers/<%= answer.id %>">Delete answer</a>
ok

2021-11-14 21:52 UTC, Ch0k commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: {answer: attributes_for(:answer), question_id: question, user_id: user} }.to change(Answer,:count).by(1)
ok

2021-11-14 22:25 UTC, Ch0k commented on app/views/questions/show.html.erb
> +    <% if answer.user == current_user %>
ok

2021-11-14 22:33 UTC, Ch0k commented on spec/features/answer/delete_spec.rb
> +    click_on 'Delete answer'
ok

2021-11-14 22:37 UTC, Ch0k commented on spec/features/question/delete_spec.rb
> +    click_on 'Delete question'
ok

2021-11-14 22:37 UTC, Ch0k commented on spec/features/answer/delete_spec.rb
> +    expect(page).to have_content "Answer deleted"
ok

2021-11-14 22:37 UTC, Ch0k commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
ok

2021-11-14 22:37 UTC, Ch0k commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: {question: attributes_for(:question, user_id: user)} }.to change(Question,:count).by(1)
ok

2021-11-14 23:04 UTC, Ch0k commented on spec/features/question/show_spec.rb
> +    answers.each do |answer|
ok

2021-11-14 23:05 UTC, Ch0k commented on spec/features/question/show_spec.rb
> +    fill_in 'Body', with: 'new answer answer answer'
ok

2021-11-14 23:07 UTC, Ch0k commented on spec/features/question/show_spec.rb
> +    expect(page).to have_content 'Answer successfuly created'
ok

2021-11-15 07:40 UTC, vkurennov requested changes

2021-11-15 07:40 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'DELETE #destroy' do
я же писал, что тут должно быть 2 контекста: для автора и для не-автора. если в коде условие, то надо тестить все возможные варианты. посмотри на тесты create, там как раз так и сделано.

2021-11-15 07:40 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: {question: attributes_for(:question, user_id: user)} }.to change(Question,:count).by(1)
в итоге параметр так и остался здесь

2021-11-15 07:40 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
ну и где исправление? не вижу 2х контекстов

2021-11-15 07:40 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    fill_in 'Body', with: 'new answer answer answer'
комментарий означал, что надо тесты создания ответа вынести в отдельную фичу-файл, как например, это сделано для вопроса

2021-11-15 07:40 UTC, vkurennov commented on app/models/user.rb
> +  def author_of?(object)
где тесты модели на этот метод?

2021-11-15 13:50 UTC, Ch0k commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
про контроллеры совсем забыл

2021-11-15 13:51 UTC, Ch0k commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: {question: attributes_for(:question, user_id: user)} }.to change(Question,:count).by(1)
удалил

2021-11-15 13:51 UTC, Ch0k commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
про контроллеры забыл. думал только про фича тесты

2021-11-15 13:51 UTC, Ch0k commented on spec/features/question/show_spec.rb
> +    fill_in 'Body', with: 'new answer answer answer'
создал отдельный файл

2021-11-15 13:52 UTC, Ch0k commented on spec/controllers/answers_controller_spec.rb
>    describe 'DELETE #destroy' do
Добавил

2021-11-17 17:11 UTC, merged